services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"

  airflow-webserver:
    image: apache/airflow:2.10.5-python3.11
    command: bash -c "sleep 10 && airflow db init && airflow users create --username airflow --password airflow --firstname Andrijana --lastname K --role Admin --email andrijana@example.com || true && airflow webserver"
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas sqlalchemy python-dotenv validators numpy psycopg2-binary"
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./.env:/opt/airflow/.env
      - ./bronze:/opt/airflow/bronze
      - ./silver:/opt/airflow/silver
      - ./gold:/opt/airflow/gold
      - ./dataEngineeringDataset.csv:/opt/airflow/dataEngineeringDataset.csv


  airflow-scheduler:
    image: apache/airflow:2.10.5-python3.11
    command: bash -c "sleep 15 && airflow scheduler"
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas sqlalchemy python-dotenv validators numpy psycopg2-binary"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./.env:/opt/airflow/.env
      - ./bronze:/opt/airflow/bronze
      - ./silver:/opt/airflow/silver
      - ./gold:/opt/airflow/gold
      - ./dataEngineeringDataset.csv:/opt/airflow/dataEngineeringDataset.csv
      
volumes:
  postgres-db-volume:
